front:
    resource: ../../src/Actions/Front/
    type: annotation

api:
    resource: ../../src/Actions/Api/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
