services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $dbpath: '%kernel.project_dir%/var/db/'
            $webRootDir: '%kernel.project_dir%/public/'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Infrastructure,Tests,Kernel.php}'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/Infrastructure/{Migrations}'

    #Actions
    App\Actions\:
        resource: '../src/Actions'
        tags: ['controller.service_arguments']
