services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Tests,Kernel.php}'

    App\Api\:
        resource: '../src/Api/*'
        exclude: '../src/Api/{Migrations}'

    #Actions
    App\Front\Actions\:
        resource: '../src/Front/Actions'
        tags: ['controller.service_arguments']

    App\Api\Actions\:
        resource: '../src/Api/Actions'
        tags: ['controller.service_arguments']
